name: Saludo automático

on:
  push:
    branches:
      - main

jobs:
  saludar-al-usuario:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código del repositorio
        uses: actions/checkout@v4

      - name: Saludar al usuario
        run: echo "¡Hola."

      - name: Listar archivos del repositorio
        run: ls -la
